### ISSUE TITLE
Issue running the demo

### ISSUE THREAD

**Issue by tjvantoll** [NathanWalker/nativescript-ezaudio#2]
Hey @NathanWalker. First of all nice work on this 😀 I’m trying to run the demo though and running into an issue. Here’s the error:

```
VANTOLLMAC-7 demo[2370]: file:///app/player/player-view-model.js:3:37: 
JS ERROR Error: Could not find module 'nativescript-ezaudio'.
Computed path '/Users/tj/Library/Developer/CoreSimulator/Devices/582F96CF-08F7-4C6D-83FC-74A77DE98560/data/Containers/Bundle/Application/1FFE49A7-F735-4D4E-A9BC-7251C3846304/demo.app/app/tns_modules/nativescript-ezaudio'.
```

Basically, it seems like, because the JS files are not included in this plugin’s npm distribution, NativeScript can’t find the appropriate file at runtime. Am I missing something here? I’ll be honest and say I haven’t built a plugin in TypeScript yet, so I’m not sure what the best practice is here.

Thanks.

**Comment by NathanWalker** [comment]
Sorry for the trouble @tjvantoll just seeing this report. I'll take a look later today and see what I can find.
Did you 'npm run build' in the root first? That will build the plugin and then you can run the demo.
See setup instructions here:
https://github.com/NathanWalker/nativescript-ezaudio/blob/master/docs/CONTRIBUTING.md

**Comment by tjvantoll** [comment]
No worries, just thought I’d post this here so you were aware. I _think_ that when you build a {N} plugin in TypeScript you must include the JS files in your npm distribution so that {N} JavaScript projects can use them, which this plugin currently does not. Let me check with the full {N} team to confirm that though.

**Comment by NathanWalker** [comment]
Indeed, the .js files need to be in the npm distribution. If they are not, that is definitely an error. Checking now.

**Comment by NathanWalker** [comment]
@tjvantoll The .js files are all there in the npm distribution. 
![screen shot 2016-02-22 at 12 14 08 pm](https://cloud.githubusercontent.com/assets/457187/13231273/f21fc2ee-d95d-11e5-87b1-810e40490a66.png)

Are you trying to run the demo in the repo?
If so, please follow `Setup` here:
https://github.com/NathanWalker/nativescript-ezaudio/blob/master/docs/CONTRIBUTING.md

If installing via npm, you should have everything you need. Please let me know otherwise.

**Comment by NathanWalker** [comment]
When I publish to `npm`, I build everything out and publish including those `.js` files.
However I `.gitignore` those `.js` files on the repo. 
What is on github here is not necessarily what is available through npm; It's the latest code, but a `built` version of the code.
The repo is just the source with instructions on how to build for those that would like to try the demo or contribute, of which contributions are certainly welcome :)

**Comment by tjvantoll** [comment]
Ah, ok. I was indeed running the demo in the repository and I completely missed your comment earlier pointing me at `npm run`. Apologies for that; I’ll close this.

I’ll try to add one thing constructive here for wasting so much of your time. On [this page](https://github.com/NathanWalker/nativescript-ezaudio/blob/master/docs/CONTRIBUTING.md#try-it) you can replace `npm install` and `tns platform add ios` with `tns install`, as `tns install` will handle both of those for you. It’ll add the Android platform too if you specify one in your `package.json`.

**Comment by NathanWalker** [comment]
No worries at all. Sweet, I just updated instructions per your suggestion (https://github.com/NathanWalker/nativescript-ezaudio/commit/4504e491ad40fbe173fecc6d968f18e3fe36c954), good to know! :+1: Thanks.

There's a lot more planned with this plugin including a Recorder. Well I plan to implement all the components that EZAudio offers, so much more to come.

Btw, if you know anyone who wants to help with an Android version of this, please share. Looking for contributors to help with Android side.
Here's a couple things that may help:
- https://github.com/Semantive/waveform-android
- https://github.com/google/ExoPlayer
- https://github.com/carlosrafaelgn/FPlayAndroid

**Comment by NathanWalker** [comment]
If Android support is possible, I'd probably need to rename the plugin and repo, maybe just 'nativescript-audio'... I'll rename if/when Android support comes.

**Comment by NathanWalker** [comment]
@tjvantoll One last thing here. For some reason, the `Slider` does not update as the playback moves ahead. I do have events for this updating the bound `value` on the Slider:
https://github.com/NathanWalker/nativescript-ezaudio/blob/master/demo/app/player/player-view-model.ts#L60-L65
https://github.com/NathanWalker/nativescript-ezaudio/blob/master/demo/app/player/player-page.xml#L14
...so not sure if this is an error with bindings and Sliders in {N} or something else?  A PR from anyone on that would be excellent.

**Comment by tjvantoll** [comment]
Gotcha. At a glance what you’re doing makes sense, so I’m not sure what’s up without a bit of digging.

**Comment by NathanWalker** [comment]
Just added an issue here about it:
https://github.com/NathanWalker/nativescript-ezaudio/issues/3
