### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by NathanWalker** [NathanWalker/nativescript-ezaudio#4]
Looking for contributors to help with Android side.
Here's a couple things that may help:
- https://github.com/Semantive/waveform-android
- https://github.com/google/ExoPlayer
- https://github.com/carlosrafaelgn/FPlayAndroid

**Comment by NathanWalker** [comment]
If Android is possible, I will rename/republish as simply `nativescript-audio`.

**Comment by ghost** [comment]
Oh, yes please! 
Please publish an android version of this amazing plugin! I would love to see that.
