### ISSUE TITLE
how can we use this with angular ?

### ISSUE THREAD

**Issue by tahir-jamil** [NathanWalker/nativescript-ezaudio#8]

**Comment by NathanWalker** [comment]
This lib has been wrapped into the amazing iOS AudioKit framework which we discuss and use the waveforms in this book:
https://www.packtpub.com/web-development/nativescript-angular-mobile-development

However this will work just fine as long as you use registerElement for the AudioPlot.

**Comment by tahir-jamil** [comment]
hm ok
